services:
  # Users
  users_db:
    image: postgres:latest
    container_name: users_db
    command: postgres -p 5001
    ports:
     - 5001:5001
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_USERS_DB}
      POSTGRES_PORT: 5001
    volumes:
      - ./.containers/users_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -p 5001"]
      interval: 5s
      timeout: 5s
      retries: 5

  users.api:
    build:
      context: Users
      dockerfile: Users.API/Dockerfile
    ports:
      - 8001:8080
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USERS_DB: ${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_AUDIENCE: ${JWT_AUDIENCE}
    depends_on:
      users_db:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: Users

  users.grpc:
    build:
      context: Users
      dockerfile: Users.gRPC/Dockerfile
    ports:
      - 8002:8080
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USERS_DB: ${POSTGRES_USERS_DB}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_AUDIENCE: ${JWT_AUDIENCE}
    depends_on:
      users_db:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: Users   

  # Surveys
  surveys_db:
    image: postgres:latest
    container_name: surveys_db
    command: postgres -p 5002
    ports:
     - 5002:5002
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_SURVEYS_DB}
      POSTGRES_PORT: 5002
    volumes:
      - ./.containers/surveys_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -p 5002"]
      interval: 5s
      timeout: 5s
      retries: 5


  surveys.rest:
    build:
      context: Surveys
      dockerfile: Surveys.REST/Dockerfile
    ports:
      - 8003:8080
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_SURVEYS_DB: ${POSTGRES_SURVEYS_DB}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_AUDIENCE: ${JWT_AUDIENCE}
    depends_on:
      surveys_db:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: Surveys


